### ISSUE TITLE
error when running the executable in cdf

### ISSUE THREAD

**Issue by Madach97** [alecjacobson/computer-graphics-shader-pipeline#15] opened 2018-11-08 23:40 UTC
I was able to build the code with cmake and make build and it worked. But when I try running the executable I get:
""
GLX: GLX version 1.3 is required
Could not create glfw window
"""
How do I fix this. I am connecting to cdf using the nx client so I can see the visual displays

**Comment by alecjacobson** [comment] 2018-11-09 14:14
duplicate of https://github.com/alecjacobson/computer-graphics-shader-pipeline/issues/1

**Closed by alecjacobson** 2018-11-09 14:14 UTC
